# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy-gh-pages

on:
  push:
    branches: [vue3]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # Checkout
      - uses: actions/checkout@v2
      # Set pnpm
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.10.0
      # use nodejs
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'pnpm'

      - run: pnpm i
      - run: pnpm run docs:build

      - name: GH Pages deploy
        # You may pin to the exact commit or the version.
        # uses: Cecilapp/GitHub-Pages-deploy@a6f0cf12a4874fbeb75f6393d0568fb3c86dda37
        uses: Cecilapp/GitHub-Pages-deploy@3.2.0
        with:
          # A verified email.
          email: hm910705@163.com
          # Where static files are.
          build_dir: docs/.vuepress/dist

